// src/components/Result.vue
<template>
    <div>
    <h1>Resultados</h1>
    <ol>
        <li v-for="option in options" :key="option.name">{{ option.name }} - {{ option.votes }} votos ({{ ((option.votes / total) * 100).toFixed(1) }}%)</li>
    </ol>
    </div>
</template>

<script>
    export default {
        props: ['options'],
        computed: {
            total() {
                if (this.options.length === 0)
                    return 1;

                return this.options.reduce((x, y) => x + y.votes, 0);
            }
        }
    }
</script>

// src/app/result.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'result',
  template: `
    <h1>Resultados</h1>
    <ol>
      <li *ngFor="let option of options">{{ option.name }} - {{ option.votes }} votos ({{ ((option.votes / getTotal()) * 100).toFixed(1) }}%)</li>
    </ol>
  `,
  styles: [
  ]
})
export class ResultComponent {
  @Input() options: any[] = []
  

  getTotal() {
    if (this.options.length === 0)
      return 1

    return this.options.reduce((x, y) => x + y.votes, 0)
  }

}
