// src/components/Booth.vue
<template>
    <div>
        <h1>{{ title }}</h1>
        <button class="button" v-for="(option, index) in options" :key="option.name" @click="$emit('vote', index)">{{ option.name }}</button>
    </div>
</template>

<script>
export default {
    props: ['title', 'options']
}
</script>

<style>
    .button {
        margin-right: 10px;
    }
</style>

// src/Booth.svelte
<h1>{title}</h1>
{#each options as option, index (option.name)}
    <button class="button" on:click="{dispatcher('vote', index)}">{option.name}</button>
{/each}

<script>
    import { createEventDispatcher } from 'svelte'

    export let options
    export let title

    const dispatcher = createEventDispatcher()
</script>

<style>
    .button {
        margin-right: 10px;
    }
</style>
