// src/components/Card.vue
<template>
    <div>
        <Booth v-if="state === 'open'" :options="options" :title="title" @vote="vote"/>
        <Result v-else :options="options" :total="total"/>
    </div>
</template>

<script>
import Booth from './Booth.vue'
import Result from './Result.vue'

const options = [{name: 'Sim', votes: 0}, {name: 'Não', votes: 0}]

export default {
    components: {Booth, Result},
    data: () => ({
        state: 'open',
        title: 'Isso é um projeto Vue?'
    }),
    methods: {
        vote(index) {
            this.state = 'closed'
            this.options[index].votes++
            console.log(this.total)
        }
    },
    computed: {
        options() {
            return options
        },
        total() {
            return options.reduce((x, y) => x + y.votes, 0)
        }
    }
}
</script>

// src/Card.svelte
<div class="card">
    {#if state === 'open'}
        <Booth {options} {title} on:vote="{vote}"/>
    {:else}
        <Result {options} {total}/>
    {/if}

</div>

<script>
    import Booth from './Booth.svelte'
    import Result from './Result.svelte'

    const options = [{name: 'Sim', votes: 0}, {name: 'Não', votes: 0}]

    let state = 'open'
    let total = options.reduce((x, y) => x + y.votes, 0);
    let title = 'Esse é um projeto Svelte?'

    function vote(index){
        options[index.detail].votes++
        total++
        state = 'closed'
    }
</script>

<style>
    .card {
        background-color: azure;
        padding: 15px;
        border-radius: 10px;
        margin: 15px;
    }
</style>
